const { items } = require("./web/public/arkitems.json");
const d = require("./web/public/arkdinos.json");
let data = [
  {
    id: 1,
    content: "aaaa",
    created_at: "2023-01-16T00:00:00.000Z",
    profile_id: 1,
  },
  {
    id: 3,
    content: "bbbbbbbbb",
    created_at: "2023-01-16T10:00:00.000Z",
    profile_id: 2,
  },
  {
    id: 2,
    content: "Hello",
    created_at: "2023-01-16T10:00:20.000Z",
    profile_id: 1,
  },
  {
    id: 4,
    content: "bruh",
    created_at: "2023-01-16T10:00:30.000Z",
    profile_id: 1,
  },
  {
    id: 5,
    content: "test123254346",
    created_at: "2023-01-16T11:00:00.000Z",
    profile_id: 1,
  },
  {
    id: 6,
    content: "test",
    created_at: "2023-01-16T12:00:00.000Z",
    profile_id: 2,
  },
];
// let d = ["aaaa", "bbbbbbbbb", "Hello", "bruh", "aaaa"];
// console.time("normal");
// const remDupicates = (arr) => {
//   return arr.filter((item, index) => arr.indexOf(item) === index);
// };

// console.log(remDupicates(d));
// console.timeEnd("normal");

// console.time("optimized");
// const removeDuplicates = (arr) => {
//   return [...new Set(arr)];
// };
// console.log(removeDuplicates(d));
// console.timeEnd("optimized");
console.log(d);
let itemss = [];
Object.values(d).forEach((item, i) => {
  const { name } = item;
  itemss.push({
    id: i + 1,
    name,
    nameTranslations: item.name_t,
    img: item.img,
    affinity: item.a0,
    synonyms: item.sy,
  });
  let level = 100;
  let comsumptionMultiplier = 1;
  let affinityNeeded = item.a0 + item.aI * level;
  let foodConsumption = item.foodBase * item.foodMult * comsumptionMultiplier;
  // let foodMax = affinityNeeded / food[name].affinity';
});
// https://www.dododex.com/api/data.json
let t = {
  "Longneck Rifle": {
    name: "Tranquilizer Dart",
    img: "Tranquilizer Dart",
    torpor: 221,
    damage: 26,
    durationDevKit: 5,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Longneck Rifle",
    type: "Longneck Rifle",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.248868778280543,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 4.497737556561086,
          hitsUntilFlee: 1,
          hits: 5,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 22.488687782805428,
          hitsUntilFlee: 1,
          hits: 23,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Shocking Tranquilizer Dart": {
    name: "Shocking Tranquilizer Dart",
    img: "Shocking Tranquilizer Dart",
    torpor: 442,
    damage: 26,
    durationDevKit: 5,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Shocking Tranquilizer Dart",
    type: "Shocking Tranquilizer Dart",
    userDamage: 100,
    data: {
      hits: 2,
      hitsRaw: 1.1244343891402715,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 2.248868778280543,
          hitsUntilFlee: 1,
          hits: 3,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 11.244343891402714,
          hitsUntilFlee: 1,
          hits: 12,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Bow: {
    name: "Bow",
    img: "Tranq Arrow Bow",
    torpor: 90,
    damage: 20,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Bow",
    type: "Bow",
    userDamage: 100,
    data: {
      hits: 6,
      hitsRaw: 5.522222222222222,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 11.044444444444444,
          hitsUntilFlee: 1,
          hits: 12,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 55.22222222222222,
          hitsUntilFlee: 1,
          hits: 56,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Crossbow: {
    name: "Crossbow",
    img: "Tranq Arrow Crossbow",
    torpor: 157.5,
    damage: 35,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Crossbow",
    type: "Crossbow",
    userDamage: 108,
    data: {
      hits: 3,
      hitsRaw: 2.921810699588477,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 5.843621399176954,
          hitsUntilFlee: 1,
          hits: 6,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 29.21810699588477,
          hitsUntilFlee: 1,
          hits: 30,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Tek Bow": {
    name: "Tek Bow",
    img: "Tek Bow",
    torpor: 336,
    damage: 24,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Tek Bow",
    type: "Tek Bow",
    userDamage: 100,
    data: {
      hits: 2,
      hitsRaw: 1.4791666666666667,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 2.9583333333333335,
          hitsUntilFlee: 1,
          hits: 3,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 14.791666666666666,
          hitsUntilFlee: 1,
          hits: 15,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Compound Bow": {
    name: "Compound Bow",
    img: "Tranq Arrow Compound",
    torpor: 121.5,
    damage: 27,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Compound Bow",
    type: "Compound Bow",
    userDamage: 100,
    data: {
      hits: 5,
      hitsRaw: 4.090534979423868,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 8.181069958847736,
          hitsUntilFlee: 1,
          hits: 9,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 40.90534979423868,
          hitsUntilFlee: 1,
          hits: 41,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Harpoon Launcher": {
    name: "Harpoon Launcher",
    img: "Harpoon Launcher",
    torpor: 300,
    damage: 36,
    duration: 5,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Harpoon Launcher",
    type: "Harpoon Launcher",
    userDamage: 111,
    data: {
      hits: 2,
      hitsRaw: 1.4924924924924925,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 2.984984984984985,
          hitsUntilFlee: 1,
          hits: 3,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 14.924924924924925,
          hitsUntilFlee: 1,
          hits: 15,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Fists: {
    name: "Fists",
    img: "Fists",
    torpor: 14,
    damage: 8,
    hasMultipler: false,
    usesMeleeDamage: true,
    mult: [
      "DmgType_Melee_Torpidity_StoneWeapon",
      "DmgType_Melee_Torpidity",
      "DmgType_Melee_Human",
      "DmgType_Melee",
      "DamageType",
    ],
    id: "Fists",
    type: "Fists",
    userDamage: 100,
    data: {
      hits: 64,
      hitsRaw: 63.673462340306,
      hitsUntilFlee: 1,
      chanceOfDeath: 97,
      chanceOfDeathHigh: true,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: false,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 127.346924680612,
          hitsUntilFlee: 1,
          hits: 128,
          chanceOfDeath: 97,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 636.73462340306,
          hitsUntilFlee: 1,
          hits: 637,
          chanceOfDeath: 95,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
      ],
    },
  },
  Slingshot: {
    name: "Slingshot",
    img: "Slingshot",
    torpor: 23.8,
    damage: 14,
    hasMultipler: true,
    mult: ["DmgType_StoneWeapon", "DamageType"],
    id: "Slingshot",
    type: "Slingshot",
    userDamage: 100,
    data: {
      hits: 29,
      hitsRaw: 28.22989539057078,
      hitsUntilFlee: 1,
      chanceOfDeath: 62,
      chanceOfDeathHigh: true,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 56.45979078114156,
          hitsUntilFlee: 1,
          hits: 57,
          chanceOfDeath: 53,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 282.2989539057078,
          hitsUntilFlee: 1,
          hits: 283,
          chanceOfDeath: 53,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
      ],
    },
  },
  "Wooden Club": {
    name: "Wooden Club",
    img: "Wooden Club",
    torpor: 20,
    damage: 5,
    hasMultipler: true,
    usesMeleeDamage: true,
    mult: [
      "DmgType_Melee_HighTorpidity_StoneWeapon",
      "DmgType_Melee_Human",
      "DmgType_StoneWeapon",
      "DamageType",
    ],
    id: "Wooden Club",
    type: "Wooden Club",
    userDamage: 100,
    data: {
      hits: 37,
      hitsRaw: 36.00027634397989,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 72.00055268795978,
          hitsUntilFlee: 1,
          hits: 73,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 360.0027634397989,
          hitsUntilFlee: 1,
          hits: 361,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Boomerang Melee": {
    name: "Boomerang (Melee)",
    img: "Boomerang Melee",
    group: "Boomerang",
    append: "(Melee)",
    damage: 30,
    torpor: 42,
    usesMeleeDamage: true,
    hide: true,
    mult: [
      "DmgType_Melee_Torpidity_StoneWeapon",
      "DmgType_Melee_Human",
      "DmgType_StoneWeapon",
      "DamageType",
    ],
    id: "Boomerang Melee",
    type: "Boomerang Melee",
    userDamage: 100,
    data: {
      hits: 14,
      hitsRaw: 13.880568623043699,
      hitsUntilFlee: 1,
      chanceOfDeath: 62,
      chanceOfDeathHigh: true,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 27.761137246087397,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 62,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 138.80568623043698,
          hitsUntilFlee: 1,
          hits: 139,
          chanceOfDeath: 62,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
      ],
    },
  },
  Boomerang: {
    name: "Boomerang",
    img: "Boomerang",
    group: "Boomerang",
    damage: 30,
    torpor: 70.5,
    mult: [
      "DmgType_Melee_Torpidity_StoneWeapon",
      "DmgType_StoneWeapon",
      "DamageType",
    ],
    id: "Boomerang",
    type: "Boomerang",
    userDamage: 100,
    data: {
      hits: 8,
      hitsRaw: 7.728738438680714,
      hitsUntilFlee: 1,
      chanceOfDeath: 0.3,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 15.457476877361428,
          hitsUntilFlee: 1,
          hits: 16,
          chanceOfDeath: 0.3,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 77.28738438680713,
          hitsUntilFlee: 1,
          hits: 78,
          chanceOfDeath: 0.3,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Electric Prod": {
    name: "Electric Prod",
    img: "Electric Prod",
    torpor: 266,
    damage: 1,
    hasMultipler: true,
    mult: ["DmgType_Melee_Human", "DamageType"],
    id: "Electric Prod",
    type: "Electric Prod",
    userDamage: 100,
    data: {
      hits: 2,
      hitsRaw: 1.9129698811163536,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 3.825939762232707,
          hitsUntilFlee: 1,
          hits: 4,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 19.129698811163536,
          hitsUntilFlee: 1,
          hits: 20,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Tripwire Narcotic Trap": {
    name: "Tripwire Narcotic Trap",
    img: "Tripwire Narcotic Trap",
    torpor: 240,
    damage: 0,
    duration: 10,
    mult: ["DamageType"],
    id: "Tripwire Narcotic Trap",
    type: "Tripwire Narcotic Trap",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.0708333333333333,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 4.141666666666667,
          hitsUntilFlee: 1,
          hits: 5,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 20.708333333333332,
          hitsUntilFlee: 1,
          hits: 21,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "S+ Tranq Turret": {
    name: "S+ Tranq Turret",
    img: "Tranq Turret",
    torpor: 250,
    damage: 0,
    duration: 0,
    mult: ["DamageType"],
    id: "S+ Tranq Turret",
    type: "S+ Tranq Turret",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.0385106274382867,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 4.077021254876573,
          hitsUntilFlee: 1,
          hits: 5,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 20.385106274382867,
          hitsUntilFlee: 1,
          hits: 21,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  EquusBuckKick: {
    name: "Equus (Buck Kick)",
    img: "Equus Buck Kick",
    damage: 11,
    torpor: 38.5,
    hasMultipler: true,
    isDino: true,
    mult: ["DmgType_Melee_Dino_Herbivore", "DamageType"],
    id: "EquusBuckKick",
    type: "EquusBuckKick",
    userDamage: 100,
    data: {
      hits: 16,
      hitsRaw: 15.38440128315086,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 30.76880256630172,
          hitsUntilFlee: 1,
          hits: 31,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 153.8440128315086,
          hitsUntilFlee: 1,
          hits: 154,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  BeelzebufoSecondary: {
    name: "Beelzebufo (Sweep)",
    img: "Beelzebufo Secondary",
    group: "Beelzebufo",
    append: "(Sweep)",
    damage: 20,
    torpor: 60,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    hide: true,
    mult: ["DamageType"],
    id: "BeelzebufoSecondary",
    type: "BeelzebufoSecondary",
    userDamage: 100,
    data: {
      hits: 9,
      hitsRaw: 8.283333333333333,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 16.566666666666666,
          hitsUntilFlee: 1,
          hits: 17,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 82.83333333333333,
          hitsUntilFlee: 1,
          hits: 83,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  BeelzebufoPrimary: {
    name: "Beelzebufo (Stab)",
    img: "Beelzebufo Primary",
    group: "Beelzebufo",
    append: "(Stab)",
    damage: 12,
    torpor: 36,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    mult: ["DamageType"],
    id: "BeelzebufoPrimary",
    type: "BeelzebufoPrimary",
    userDamage: 100,
    data: {
      hits: 14,
      hitsRaw: 13.805555555555555,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 27.61111111111111,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 138.05555555555554,
          hitsUntilFlee: 1,
          hits: 139,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Basilisk: {
    name: "Basilisk",
    img: "Basilisk",
    damage: 55,
    torpor: 165,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    mult: ["DamageType"],
    id: "Basilisk",
    type: "Basilisk",
    userDamage: 100,
    data: {
      hits: 4,
      hitsRaw: 3.012121212121212,
      hitsUntilFlee: 1,
      chanceOfDeath: 0.1,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 6.024242424242424,
          hitsUntilFlee: 1,
          hits: 7,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 30.12121212121212,
          hitsUntilFlee: 1,
          hits: 31,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Pulmonoscorpius: {
    name: "Pulmonoscorpius",
    img: "Pulmonoscorpius",
    damage: 15,
    torpor: 45,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    mult: ["DamageType"],
    id: "Pulmonoscorpius",
    type: "Pulmonoscorpius",
    userDamage: 100,
    data: {
      hits: 12,
      hitsRaw: 11.044444444444444,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 22.08888888888889,
          hitsUntilFlee: 1,
          hits: 23,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 110.44444444444444,
          hitsUntilFlee: 1,
          hits: 111,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  PachySecondary: {
    name: "Pachy (Charge)",
    img: "Pachy Secondary",
    group: "Pachy",
    append: "(Charge)",
    damage: 17,
    torpor: 59.5,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    hide: true,
    mult: ["DmgType_Melee_Dino_Herbivore", "DamageType"],
    id: "PachySecondary",
    type: "PachySecondary",
    userDamage: 100,
    data: {
      hits: 9,
      hitsRaw: 8.352941176470589,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 16.705882352941178,
          hitsUntilFlee: 1,
          hits: 17,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 83.52941176470588,
          hitsUntilFlee: 1,
          hits: 84,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  PachyPrimary: {
    name: "Pachy (Primary Attack)",
    img: "Pachy Primary",
    group: "Pachy",
    append: "(Primary Attack)",
    damage: 11,
    torpor: 10,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    mult: ["DmgType_Melee_Dino_Herbivore", "DamageType"],
    id: "PachyPrimary",
    type: "PachyPrimary",
    userDamage: 100,
    data: {
      hits: 50,
      hitsRaw: 49.7,
      hitsUntilFlee: 1,
      chanceOfDeath: 99,
      chanceOfDeathHigh: true,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: false,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 99.4,
          hitsUntilFlee: 1,
          hits: 100,
          chanceOfDeath: 99,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 497,
          hitsUntilFlee: 1,
          hits: 497,
          chanceOfDeath: 99,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
      ],
    },
  },
  ThornyDragon: {
    name: "Thorny Dragon (Tail Needles)",
    img: "Thorny Dragon Tail Needles",
    damage: 1,
    torpor: 4,
    duration: 5,
    hasMultipler: true,
    isDino: true,
    mult: ["DmgType_Melee_Dino_Herbivore", "DamageType"],
    id: "ThornyDragon",
    type: "ThornyDragon",
    userDamage: 100,
    data: {
      hits: 125,
      hitsRaw: 124.25,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 248.5,
          hitsUntilFlee: 1,
          hits: 249,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 1242.5,
          hitsUntilFlee: 1,
          hits: 1243,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Tusoteuthis: {
    name: "Tusoteuthis (In Seconds)",
    img: "Tusoteuthis",
    damage: 0,
    torpor: 10,
    duration: 999,
    hasMultipler: false,
    isDino: true,
    mult: ["DamageType"],
    id: "Tusoteuthis",
    type: "Tusoteuthis",
    userDamage: 100,
    data: {
      hits: 50,
      hitsRaw: 49.7,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 99.4,
          hitsUntilFlee: 1,
          hits: 100,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 497,
          hitsUntilFlee: 1,
          hits: 497,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Bow Toxicant": {
    name: "Bow (Toxicant Arrow)",
    img: "Toxicant Arrow Bow",
    torpor: 180,
    damage: 20,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Bow Toxicant",
    type: "Bow Toxicant",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.761111111111111,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 5.522222222222222,
          hitsUntilFlee: 1,
          hits: 6,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 27.61111111111111,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Compound Bow Toxicant": {
    name: "Compound Bow (Toxicant Arrow)",
    img: "Toxicant Arrow Compound",
    torpor: 245,
    damage: 27,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Compound Bow Toxicant",
    type: "Compound Bow Toxicant",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.0285714285714285,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 4.057142857142857,
          hitsUntilFlee: 1,
          hits: 5,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 20.285714285714285,
          hitsUntilFlee: 1,
          hits: 21,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Crossbow Toxicant": {
    name: "Crossbow (Toxicant Arrow)",
    img: "Toxicant Arrow Crossbow",
    torpor: 180,
    damage: 20,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Crossbow Toxicant",
    type: "Crossbow Toxicant",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.761111111111111,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 5.522222222222222,
          hitsUntilFlee: 1,
          hits: 6,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 27.61111111111111,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Longbow: {
    name: "Longbow",
    img: "Longbow",
    torpor: 75,
    damage: 30,
    duration: 5,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Longbow",
    type: "Longbow",
    userDamage: 100,
    data: {
      hits: 7,
      hitsRaw: 6.626666666666667,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 13.253333333333334,
          hitsUntilFlee: 1,
          hits: 14,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 66.26666666666667,
          hitsUntilFlee: 1,
          hits: 67,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Recurve Bow": {
    name: "Recurve Bow",
    img: "Recurve Bow",
    torpor: 180,
    damage: 40,
    duration: 4,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Recurve Bow",
    type: "Recurve Bow",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.7802470897470144,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 5.560494179494029,
          hitsUntilFlee: 1,
          hits: 6,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 27.802470897470144,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  CannonBall: {
    name: "Cannon Ball",
    img: "Cannon Ball",
    torpor: 1800,
    damage: 1800,
    duration: 1,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_CannonBall"],
  },
  Boulder: {
    name: "Boulder",
    img: "Boulder",
    torpor: 6,
    damage: 6,
    duration: 1,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_Boulder"],
  },
  BoulderKarkinos: {
    name: "Boulder",
    img: "Boulder",
    torpor: 437,
    damage: 250,
    duration: 1,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_Boulder"],
  },
  CannonBallKarkinos: {
    name: "Cannon Ball",
    img: "Cannon Ball",
    torpor: 11200,
    damage: 2250,
    duration: 1,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_CannonBall"],
  },
  "Rocket Propelled Grenade": {
    name: "Rocket Propelled Grenade",
    img: "Rocket Propelled Grenade",
    torpor: 403,
    damage: 403,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_Rocket"],
  },
  MSCM: {
    name: "M.S.C.M.",
    img: "MSCM",
    torpor: 7200,
    damage: 1500,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
  },
};

let itew = {
  "Longneck Rifle": {
    name: "Tranquilizer Dart",
    img: "Tranquilizer Dart",
    torpor: 221,
    damage: 26,
    durationDevKit: 5,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Longneck Rifle",
    type: "Longneck Rifle",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.248868778280543,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 4.497737556561086,
          hitsUntilFlee: 1,
          hits: 5,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 22.488687782805428,
          hitsUntilFlee: 1,
          hits: 23,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Shocking Tranquilizer Dart": {
    name: "Shocking Tranquilizer Dart",
    img: "Shocking Tranquilizer Dart",
    torpor: 442,
    damage: 26,
    durationDevKit: 5,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Shocking Tranquilizer Dart",
    type: "Shocking Tranquilizer Dart",
    userDamage: 100,
    data: {
      hits: 2,
      hitsRaw: 1.1244343891402715,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 2.248868778280543,
          hitsUntilFlee: 1,
          hits: 3,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 11.244343891402714,
          hitsUntilFlee: 1,
          hits: 12,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Bow: {
    name: "Bow",
    img: "Tranq Arrow Bow",
    torpor: 90,
    damage: 20,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Bow",
    type: "Bow",
    userDamage: 100,
    data: {
      hits: 6,
      hitsRaw: 5.522222222222222,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 11.044444444444444,
          hitsUntilFlee: 1,
          hits: 12,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 55.22222222222222,
          hitsUntilFlee: 1,
          hits: 56,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Crossbow: {
    name: "Crossbow",
    img: "Tranq Arrow Crossbow",
    torpor: 157.5,
    damage: 35,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Crossbow",
    type: "Crossbow",
    userDamage: 108,
    data: {
      hits: 3,
      hitsRaw: 2.921810699588477,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 5.843621399176954,
          hitsUntilFlee: 1,
          hits: 6,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 29.21810699588477,
          hitsUntilFlee: 1,
          hits: 30,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Tek Bow": {
    name: "Tek Bow",
    img: "Tek Bow",
    torpor: 336,
    damage: 24,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Tek Bow",
    type: "Tek Bow",
    userDamage: 100,
    data: {
      hits: 2,
      hitsRaw: 1.4791666666666667,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 2.9583333333333335,
          hitsUntilFlee: 1,
          hits: 3,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 14.791666666666666,
          hitsUntilFlee: 1,
          hits: 15,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Compound Bow": {
    name: "Compound Bow",
    img: "Tranq Arrow Compound",
    torpor: 121.5,
    damage: 27,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Compound Bow",
    type: "Compound Bow",
    userDamage: 100,
    data: {
      hits: 5,
      hitsRaw: 4.090534979423868,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 8.181069958847736,
          hitsUntilFlee: 1,
          hits: 9,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 40.90534979423868,
          hitsUntilFlee: 1,
          hits: 41,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Harpoon Launcher": {
    name: "Harpoon Launcher",
    img: "Harpoon Launcher",
    torpor: 300,
    damage: 36,
    duration: 5,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Harpoon Launcher",
    type: "Harpoon Launcher",
    userDamage: 111,
    data: {
      hits: 2,
      hitsRaw: 1.4924924924924925,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 2.984984984984985,
          hitsUntilFlee: 1,
          hits: 3,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 14.924924924924925,
          hitsUntilFlee: 1,
          hits: 15,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Fists: {
    name: "Fists",
    img: "Fists",
    torpor: 14,
    damage: 8,
    hasMultipler: false,
    usesMeleeDamage: true,
    mult: [
      "DmgType_Melee_Torpidity_StoneWeapon",
      "DmgType_Melee_Torpidity",
      "DmgType_Melee_Human",
      "DmgType_Melee",
      "DamageType",
    ],
    id: "Fists",
    type: "Fists",
    userDamage: 100,
    data: {
      hits: 64,
      hitsRaw: 63.673462340306,
      hitsUntilFlee: 1,
      chanceOfDeath: 97,
      chanceOfDeathHigh: true,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: false,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 127.346924680612,
          hitsUntilFlee: 1,
          hits: 128,
          chanceOfDeath: 97,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 636.73462340306,
          hitsUntilFlee: 1,
          hits: 637,
          chanceOfDeath: 95,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
      ],
    },
  },
  Slingshot: {
    name: "Slingshot",
    img: "Slingshot",
    torpor: 23.8,
    damage: 14,
    hasMultipler: true,
    mult: ["DmgType_StoneWeapon", "DamageType"],
    id: "Slingshot",
    type: "Slingshot",
    userDamage: 100,
    data: {
      hits: 29,
      hitsRaw: 28.22989539057078,
      hitsUntilFlee: 1,
      chanceOfDeath: 62,
      chanceOfDeathHigh: true,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 56.45979078114156,
          hitsUntilFlee: 1,
          hits: 57,
          chanceOfDeath: 53,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 282.2989539057078,
          hitsUntilFlee: 1,
          hits: 283,
          chanceOfDeath: 53,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
      ],
    },
  },
  "Wooden Club": {
    name: "Wooden Club",
    img: "Wooden Club",
    torpor: 20,
    damage: 5,
    hasMultipler: true,
    usesMeleeDamage: true,
    mult: [
      "DmgType_Melee_HighTorpidity_StoneWeapon",
      "DmgType_Melee_Human",
      "DmgType_StoneWeapon",
      "DamageType",
    ],
    id: "Wooden Club",
    type: "Wooden Club",
    userDamage: 100,
    data: {
      hits: 37,
      hitsRaw: 36.00027634397989,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 72.00055268795978,
          hitsUntilFlee: 1,
          hits: 73,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 360.0027634397989,
          hitsUntilFlee: 1,
          hits: 361,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Boomerang Melee": {
    name: "Boomerang (Melee)",
    img: "Boomerang Melee",
    group: "Boomerang",
    append: "(Melee)",
    damage: 30,
    torpor: 42,
    usesMeleeDamage: true,
    hide: true,
    mult: [
      "DmgType_Melee_Torpidity_StoneWeapon",
      "DmgType_Melee_Human",
      "DmgType_StoneWeapon",
      "DamageType",
    ],
    id: "Boomerang Melee",
    type: "Boomerang Melee",
    userDamage: 100,
    data: {
      hits: 14,
      hitsRaw: 13.880568623043699,
      hitsUntilFlee: 1,
      chanceOfDeath: 62,
      chanceOfDeathHigh: true,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 27.761137246087397,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 62,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 138.80568623043698,
          hitsUntilFlee: 1,
          hits: 139,
          chanceOfDeath: 62,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
      ],
    },
  },
  Boomerang: {
    name: "Boomerang",
    img: "Boomerang",
    group: "Boomerang",
    damage: 30,
    torpor: 70.5,
    mult: [
      "DmgType_Melee_Torpidity_StoneWeapon",
      "DmgType_StoneWeapon",
      "DamageType",
    ],
    id: "Boomerang",
    type: "Boomerang",
    userDamage: 100,
    data: {
      hits: 8,
      hitsRaw: 7.728738438680714,
      hitsUntilFlee: 1,
      chanceOfDeath: 0.3,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 15.457476877361428,
          hitsUntilFlee: 1,
          hits: 16,
          chanceOfDeath: 0.3,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 77.28738438680713,
          hitsUntilFlee: 1,
          hits: 78,
          chanceOfDeath: 0.3,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Electric Prod": {
    name: "Electric Prod",
    img: "Electric Prod",
    torpor: 266,
    damage: 1,
    hasMultipler: true,
    mult: ["DmgType_Melee_Human", "DamageType"],
    id: "Electric Prod",
    type: "Electric Prod",
    userDamage: 100,
    data: {
      hits: 2,
      hitsRaw: 1.9129698811163536,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 3.825939762232707,
          hitsUntilFlee: 1,
          hits: 4,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 19.129698811163536,
          hitsUntilFlee: 1,
          hits: 20,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Tripwire Narcotic Trap": {
    name: "Tripwire Narcotic Trap",
    img: "Tripwire Narcotic Trap",
    torpor: 240,
    damage: 0,
    duration: 10,
    mult: ["DamageType"],
    id: "Tripwire Narcotic Trap",
    type: "Tripwire Narcotic Trap",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.0708333333333333,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 4.141666666666667,
          hitsUntilFlee: 1,
          hits: 5,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 20.708333333333332,
          hitsUntilFlee: 1,
          hits: 21,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "S+ Tranq Turret": {
    name: "S+ Tranq Turret",
    img: "Tranq Turret",
    torpor: 250,
    damage: 0,
    duration: 0,
    mult: ["DamageType"],
    id: "S+ Tranq Turret",
    type: "S+ Tranq Turret",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.0385106274382867,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 4.077021254876573,
          hitsUntilFlee: 1,
          hits: 5,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 20.385106274382867,
          hitsUntilFlee: 1,
          hits: 21,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  EquusBuckKick: {
    name: "Equus (Buck Kick)",
    img: "Equus Buck Kick",
    damage: 11,
    torpor: 38.5,
    hasMultipler: true,
    isDino: true,
    mult: ["DmgType_Melee_Dino_Herbivore", "DamageType"],
    id: "EquusBuckKick",
    type: "EquusBuckKick",
    userDamage: 100,
    data: {
      hits: 16,
      hitsRaw: 15.38440128315086,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 30.76880256630172,
          hitsUntilFlee: 1,
          hits: 31,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 153.8440128315086,
          hitsUntilFlee: 1,
          hits: 154,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  BeelzebufoSecondary: {
    name: "Beelzebufo (Sweep)",
    img: "Beelzebufo Secondary",
    group: "Beelzebufo",
    append: "(Sweep)",
    damage: 20,
    torpor: 60,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    hide: true,
    mult: ["DamageType"],
    id: "BeelzebufoSecondary",
    type: "BeelzebufoSecondary",
    userDamage: 100,
    data: {
      hits: 9,
      hitsRaw: 8.283333333333333,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 16.566666666666666,
          hitsUntilFlee: 1,
          hits: 17,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 82.83333333333333,
          hitsUntilFlee: 1,
          hits: 83,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  BeelzebufoPrimary: {
    name: "Beelzebufo (Stab)",
    img: "Beelzebufo Primary",
    group: "Beelzebufo",
    append: "(Stab)",
    damage: 12,
    torpor: 36,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    mult: ["DamageType"],
    id: "BeelzebufoPrimary",
    type: "BeelzebufoPrimary",
    userDamage: 100,
    data: {
      hits: 14,
      hitsRaw: 13.805555555555555,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 27.61111111111111,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 138.05555555555554,
          hitsUntilFlee: 1,
          hits: 139,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Basilisk: {
    name: "Basilisk",
    img: "Basilisk",
    damage: 55,
    torpor: 165,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    mult: ["DamageType"],
    id: "Basilisk",
    type: "Basilisk",
    userDamage: 100,
    data: {
      hits: 4,
      hitsRaw: 3.012121212121212,
      hitsUntilFlee: 1,
      chanceOfDeath: 0.1,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 6.024242424242424,
          hitsUntilFlee: 1,
          hits: 7,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 30.12121212121212,
          hitsUntilFlee: 1,
          hits: 31,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Pulmonoscorpius: {
    name: "Pulmonoscorpius",
    img: "Pulmonoscorpius",
    damage: 15,
    torpor: 45,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    mult: ["DamageType"],
    id: "Pulmonoscorpius",
    type: "Pulmonoscorpius",
    userDamage: 100,
    data: {
      hits: 12,
      hitsRaw: 11.044444444444444,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 22.08888888888889,
          hitsUntilFlee: 1,
          hits: 23,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 110.44444444444444,
          hitsUntilFlee: 1,
          hits: 111,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  PachySecondary: {
    name: "Pachy (Charge)",
    img: "Pachy Secondary",
    group: "Pachy",
    append: "(Charge)",
    damage: 17,
    torpor: 59.5,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    hide: true,
    mult: ["DmgType_Melee_Dino_Herbivore", "DamageType"],
    id: "PachySecondary",
    type: "PachySecondary",
    userDamage: 100,
    data: {
      hits: 9,
      hitsRaw: 8.352941176470589,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 16.705882352941178,
          hitsUntilFlee: 1,
          hits: 17,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 83.52941176470588,
          hitsUntilFlee: 1,
          hits: 84,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  PachyPrimary: {
    name: "Pachy (Primary Attack)",
    img: "Pachy Primary",
    group: "Pachy",
    append: "(Primary Attack)",
    damage: 11,
    torpor: 10,
    duration: 10,
    hasMultipler: true,
    isDino: true,
    mult: ["DmgType_Melee_Dino_Herbivore", "DamageType"],
    id: "PachyPrimary",
    type: "PachyPrimary",
    userDamage: 100,
    data: {
      hits: 50,
      hitsRaw: 49.7,
      hitsUntilFlee: 1,
      chanceOfDeath: 99,
      chanceOfDeathHigh: true,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: false,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 99.4,
          hitsUntilFlee: 1,
          hits: 100,
          chanceOfDeath: 99,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 497,
          hitsUntilFlee: 1,
          hits: 497,
          chanceOfDeath: 99,
          isPossible: true,
          chanceOfDeathHigh: true,
        },
      ],
    },
  },
  ThornyDragon: {
    name: "Thorny Dragon (Tail Needles)",
    img: "Thorny Dragon Tail Needles",
    damage: 1,
    torpor: 4,
    duration: 5,
    hasMultipler: true,
    isDino: true,
    mult: ["DmgType_Melee_Dino_Herbivore", "DamageType"],
    id: "ThornyDragon",
    type: "ThornyDragon",
    userDamage: 100,
    data: {
      hits: 125,
      hitsRaw: 124.25,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 248.5,
          hitsUntilFlee: 1,
          hits: 249,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 1242.5,
          hitsUntilFlee: 1,
          hits: 1243,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Tusoteuthis: {
    name: "Tusoteuthis (In Seconds)",
    img: "Tusoteuthis",
    damage: 0,
    torpor: 10,
    duration: 999,
    hasMultipler: false,
    isDino: true,
    mult: ["DamageType"],
    id: "Tusoteuthis",
    type: "Tusoteuthis",
    userDamage: 100,
    data: {
      hits: 50,
      hitsRaw: 49.7,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 99.4,
          hitsUntilFlee: 1,
          hits: 100,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 497,
          hitsUntilFlee: 1,
          hits: 497,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Bow Toxicant": {
    name: "Bow (Toxicant Arrow)",
    img: "Toxicant Arrow Bow",
    torpor: 180,
    damage: 20,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Bow Toxicant",
    type: "Bow Toxicant",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.761111111111111,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 5.522222222222222,
          hitsUntilFlee: 1,
          hits: 6,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 27.61111111111111,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Compound Bow Toxicant": {
    name: "Compound Bow (Toxicant Arrow)",
    img: "Toxicant Arrow Compound",
    torpor: 245,
    damage: 27,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Compound Bow Toxicant",
    type: "Compound Bow Toxicant",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.0285714285714285,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 4.057142857142857,
          hitsUntilFlee: 1,
          hits: 5,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 20.285714285714285,
          hitsUntilFlee: 1,
          hits: 21,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Crossbow Toxicant": {
    name: "Crossbow (Toxicant Arrow)",
    img: "Toxicant Arrow Crossbow",
    torpor: 180,
    damage: 20,
    duration: 6,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Crossbow Toxicant",
    type: "Crossbow Toxicant",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.761111111111111,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 5.522222222222222,
          hitsUntilFlee: 1,
          hits: 6,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 27.61111111111111,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  Longbow: {
    name: "Longbow",
    img: "Longbow",
    torpor: 75,
    damage: 30,
    duration: 5,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Longbow",
    type: "Longbow",
    userDamage: 100,
    data: {
      hits: 7,
      hitsRaw: 6.626666666666667,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 13.253333333333334,
          hitsUntilFlee: 1,
          hits: 14,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 66.26666666666667,
          hitsUntilFlee: 1,
          hits: 67,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  "Recurve Bow": {
    name: "Recurve Bow",
    img: "Recurve Bow",
    torpor: 180,
    damage: 40,
    duration: 4,
    hasMultipler: true,
    mult: ["DmgType_Projectile", "DamageType"],
    id: "Recurve Bow",
    type: "Recurve Bow",
    userDamage: 100,
    data: {
      hits: 3,
      hitsRaw: 2.7802470897470144,
      hitsUntilFlee: 1,
      chanceOfDeath: 0,
      chanceOfDeathHigh: false,
      minChanceOfDeath: 0,
      isPossible: true,
      isRecommended: true,
      hitboxes: [
        {
          name: "",
          multiplier: 0.5,
          hitsRaw: 5.560494179494029,
          hitsUntilFlee: 1,
          hits: 6,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
        {
          name: "",
          multiplier: 0.1,
          hitsRaw: 27.802470897470144,
          hitsUntilFlee: 1,
          hits: 28,
          chanceOfDeath: 0,
          isPossible: true,
          chanceOfDeathHigh: false,
        },
      ],
    },
  },
  CannonBall: {
    name: "Cannon Ball",
    img: "Cannon Ball",
    torpor: 1800,
    damage: 1800,
    duration: 1,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_CannonBall"],
  },
  Boulder: {
    name: "Boulder",
    img: "Boulder",
    torpor: 6,
    damage: 6,
    duration: 1,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_Boulder"],
  },
  BoulderKarkinos: {
    name: "Boulder",
    img: "Boulder",
    torpor: 437,
    damage: 250,
    duration: 1,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_Boulder"],
  },
  CannonBallKarkinos: {
    name: "Cannon Ball",
    img: "Cannon Ball",
    torpor: 11200,
    damage: 2250,
    duration: 1,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_CannonBall"],
  },
  "Rocket Propelled Grenade": {
    name: "Rocket Propelled Grenade",
    img: "Rocket Propelled Grenade",
    torpor: 403,
    damage: 403,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
    mult: ["Special_Raid_Rocket"],
  },
  MSCM: {
    name: "M.S.C.M.",
    img: "MSCM",
    torpor: 7200,
    damage: 1500,
    hide: true,
    disable: true,
    hasMultipler: false,
    usesMeleeDamage: false,
  },
};
