export const schema = gql`
  """
  This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
  This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
  """
  type TimelineSeason {
    "Description for id."
    id: String!

    "Description for created_at."
    created_at: DateTime

    "Description for updated_at."
    updated_at: DateTime

    "Description for server."
    server: String

    "Description for season."
    season: String

    "Description for tribe_name."
    tribe_name: String

    "Description for season_start_date."
    season_start_date: DateTime

    "Description for season_end_date."
    season_end_date: DateTime

    "Description for cluster."
    cluster: String

    "Description for timeline_id."
    timeline_id: String!

    "Description for Timeline."
    Timeline: Timeline!

    "Description for TimelineSeasonEvent."
    TimelineSeasonEvent: [TimelineSeasonEvent]!
  }

  """
  About queries
  """
  type Query {
    "Fetch TimelineSeasons."
    timelineSeasons: [TimelineSeason!]! @requireAuth

    "Fetch a TimelineSeason by id."
    timelineSeason(id: String!): TimelineSeason @requireAuth
  }

  """
  Autogenerated input type of InputTimelineSeason.
  """
  input CreateTimelineSeasonInput {
    "Description for created_at."
    created_at: DateTime

    "Description for updated_at."
    updated_at: DateTime

    "Description for server."
    server: String

    "Description for season."
    season: String

    "Description for tribe_name."
    tribe_name: String

    "Description for season_start_date."
    season_start_date: DateTime

    "Description for season_end_date."
    season_end_date: DateTime

    "Description for cluster."
    cluster: String

    "Description for timeline_id."
    timeline_id: String!
  }

  """
  Autogenerated input type of UpdateTimelineSeason.
  """
  input UpdateTimelineSeasonInput {
    "Description for created_at."
    created_at: DateTime

    "Description for updated_at."
    updated_at: DateTime

    "Description for server."
    server: String

    "Description for season."
    season: String

    "Description for tribe_name."
    tribe_name: String

    "Description for season_start_date."
    season_start_date: DateTime

    "Description for season_end_date."
    season_end_date: DateTime

    "Description for cluster."
    cluster: String

    "Description for timeline_id."
    timeline_id: String
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new TimelineSeason."
    createTimelineSeason(input: CreateTimelineSeasonInput!): TimelineSeason!
      @requireAuth

    "Updates an existing TimelineSeason."
    updateTimelineSeason(
      id: String!
      input: UpdateTimelineSeasonInput!
    ): TimelineSeason! @requireAuth

    "Deletes an existing TimelineSeason."
    deleteTimelineSeason(id: String!): TimelineSeason! @requireAuth
  }
`
