export const schema = gql`
  """
  This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
  This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
  """
  type TimelineSeasonEvent {
    "Description for id."
    id: String!

    "Description for created_at."
    created_at: DateTime

    "Description for updated_at."
    updated_at: DateTime

    "Description for timeline_season_id."
    timeline_season_id: String!

    "Description for title."
    title: String

    "Description for content."
    content: String

    "Description for map_id."
    map_id: BigInt

    "Description for latitude."
    latitude: Float

    "Description for longitude."
    longitude: Float

    "Description for images."
    images: String

    "Description for created_by."
    created_by: String

    "Description for tags."
    tags: String

    "Description for Profile."
    Profile: Profile

    "Description for Map."
    Map: Map

    "Description for TimelineSeason."
    TimelineSeason: TimelineSeason!
  }

  """
  About queries
  """
  type Query {
    "Fetch TimelineSeasonEvents."
    timelineSeasonEvents(timeline_season_id: String!): [TimelineSeasonEvent!]!
      @requireAuth

    "Fetch a TimelineSeasonEvent by id."
    timelineSeasonEvent(id: String!): TimelineSeasonEvent @requireAuth
  }

  """
  Autogenerated input type of InputTimelineSeasonEvent.
  """
  input CreateTimelineSeasonEventInput {
    "Description for created_at."
    created_at: DateTime

    "Description for updated_at."
    updated_at: DateTime

    "Description for timeline_season_id."
    timeline_season_id: String!

    "Description for title."
    title: String

    "Description for content."
    content: String

    "Description for map_id."
    map_id: BigInt

    "Description for latitude."
    latitude: Float

    "Description for longitude."
    longitude: Float

    "Description for images."
    images: String

    "Description for created_by."
    created_by: String

    "Description for tags."
    tags: String
  }

  """
  Autogenerated input type of UpdateTimelineSeasonEvent.
  """
  input UpdateTimelineSeasonEventInput {
    "Description for created_at."
    created_at: DateTime

    "Description for updated_at."
    updated_at: DateTime

    "Description for timeline_season_id."
    timeline_season_id: String

    "Description for title."
    title: String

    "Description for content."
    content: String

    "Description for map_id."
    map_id: BigInt

    "Description for latitude."
    latitude: Float

    "Description for longitude."
    longitude: Float

    "Description for images."
    images: String

    "Description for created_by."
    created_by: String

    "Description for tags."
    tags: String
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new TimelineSeasonEvent."
    createTimelineSeasonEvent(
      input: CreateTimelineSeasonEventInput!
    ): TimelineSeasonEvent!
      @requireAuth
      @hasPermission(permission: "timeline_create")

    "Updates an existing TimelineSeasonEvent."
    updateTimelineSeasonEvent(
      id: String!
      input: UpdateTimelineSeasonEventInput!
    ): TimelineSeasonEvent!
      @requireAuth
      @hasPermission(permission: "timeline_update")

    "Deletes an existing TimelineSeasonEvent."
    deleteTimelineSeasonEvent(id: String!): TimelineSeasonEvent!
      @requireAuth
      @hasPermission(permission: "timeline_delete")
  }
`;
