export const schema = gql`
  """
  This table contains check constraints and requires additional setup for migrations. Visit https://pris.ly/d/check-constraints for more info.
  This model or at least one of its fields has comments in the database, and requires an additional setup for migrations: Read more: https://pris.ly/d/database-comments
  This model contains row level security and requires additional setup for migrations. Visit https://pris.ly/d/row-level-security for more info.
  """
  type TimelineSeasonBasespot {
    "Description for id."
    id: BigInt!

    "Description for created_at."
    created_at: DateTime

    "Description for updated_at."
    updated_at: DateTime

    "Description for start_date."
    start_date: DateTime

    "Description for end_date."
    end_date: DateTime

    "Description for basespot_id."
    basespot_id: BigInt

    "Description for map."
    map: BigInt

    "Description for created_by."
    created_by: String

    "Description for latitude."
    latitude: Float

    "Description for longitude."
    longitude: Float

    "Description for timeline_season_id."
    timeline_season_id: String

    "Description for Basespot."
    Basespot: Basespot

    "Description for Profile."
    Profile: Profile

    "Description for Map."
    Map: Map

    "Description for TimelineSeason."
    TimelineSeason: TimelineSeason
  }

  """
  About queries
  """
  type Query {
    "Fetch TimelineSeasonBasespots."
    timelineSeasonBasespots: [TimelineSeasonBasespot!]! @requireAuth

    "Fetch a TimelineSeasonBasespot by id."
    timelineSeasonBasespot(id: BigInt!): TimelineSeasonBasespot @requireAuth
  }

  """
  Autogenerated input type of InputTimelineSeasonBasespot.
  """
  input CreateTimelineSeasonBasespotInput {
    "Description for created_at."
    created_at: DateTime

    "Description for updated_at."
    updated_at: DateTime

    "Description for start_date."
    start_date: DateTime

    "Description for end_date."
    end_date: DateTime

    "Description for basespot_id."
    basespot_id: BigInt

    "Description for map."
    map: BigInt

    "Description for created_by."
    created_by: String

    "Description for latitude."
    latitude: Float

    "Description for longitude."
    longitude: Float

    "Description for timeline_season_id."
    timeline_season_id: String
  }

  """
  Autogenerated input type of UpdateTimelineSeasonBasespot.
  """
  input UpdateTimelineSeasonBasespotInput {
    "Description for created_at."
    created_at: DateTime

    "Description for updated_at."
    updated_at: DateTime

    "Description for start_date."
    start_date: DateTime

    "Description for end_date."
    end_date: DateTime

    "Description for basespot_id."
    basespot_id: BigInt

    "Description for map."
    map: BigInt

    "Description for created_by."
    created_by: String

    "Description for latitude."
    latitude: Float

    "Description for longitude."
    longitude: Float

    "Description for timeline_season_id."
    timeline_season_id: String
  }

  """
  About mutations
  """
  type Mutation {
    "Creates a new TimelineSeasonBasespot."
    createTimelineSeasonBasespot(
      input: CreateTimelineSeasonBasespotInput!
    ): TimelineSeasonBasespot! @requireAuth

    "Updates an existing TimelineSeasonBasespot."
    updateTimelineSeasonBasespot(
      id: BigInt!
      input: UpdateTimelineSeasonBasespotInput!
    ): TimelineSeasonBasespot! @requireAuth

    "Deletes an existing TimelineSeasonBasespot."
    deleteTimelineSeasonBasespot(id: BigInt!): TimelineSeasonBasespot!
      @requireAuth
  }
`
