#==
# Build
FROM node:14-alpine as build

WORKDIR /app

COPY package.json .
COPY yarn.lock .

COPY api/package.json api/package.json

RUN yarn install --frozen-lockfile

COPY redwood.toml .
COPY graphql.config.js .
COPY babel.config.js .

COPY api api
RUN yarn rw build api

#==
# Serve
FROM node:14-alpine

WORKDIR /app

COPY api/package.json api/package.json

RUN yarn install && yarn add react react-dom @redwoodjs/api-server @redwoodjs/internal

COPY graphql.config.js .
COPY redwood.toml .
COPY api api

COPY --from=build /app/api/dist /app/api/dist
COPY --from=build /app/node_modules/.prisma /app/node_modules/.prisma

EXPOSE 8911

CMD [ "yarn", "rw-api-server", "--port", "8911" ]